---
title: Che 程序集
sidebar: che_6_docs
keywords: dev docs
tags: [extensions, assembly]
permalink: che-6/assemblies.html
redirect_from: assemblies.html
folder: che-6/developer-guide
---


[id="what-is-a-che-assembly"]
== Che 程序集是什么？

程序集是一个产生构建工件的Maven模块。对 https://github.com/eclipse/che/tree/master/assembly[Eclipse Che] 来说，或者是一个带有多个 `jars` 包的 `war` 文件，或者是一个Tomcat程序集，是一个把自定义的配置和工件拷贝到 `webapps`下的Tomcat Web 服务器。下面这些是Eclipse Che 程序集：

[width="100%",cols="61%,39%",options="header",]
|===
|Che 程序集 |包含的内容
|`assembly-ide-war` |GWT 插件，它被作为javascript编译进一个新的浏览器 IDE
|`assembly-wsagent-war` |Java 插件，它作为运行在工作空间的agent中，作为带有许多个jar包的 `.war` 部署。
|`assembly-wsagent-server` |把工作空间agent打包到Tomcat中，然后Tomcat在机器中运行
|`assembly-wsmaster-war` |Java 插件，它运行于Che内核服务器中 - 主服务(master)
|`assembly-main` |打包所有的Che模块（含上述所有）到最终的Tomcat集束(bundle)
|===

[id="assembly-ide-war"]
== assembly-ide-war

成功的构建这个模块会生成 `ide.war`, 它将以 `ROOT.war` 被部署到Tomcat(由 `assembly-main` 产生)中。 其中包含了少数的所依赖的jar，更重要的内容是 `_app` 目录，里面包含了Javascript, CSS及其它的资源，IDE在初始化时将它们加载到 `IDE.html` 中。

这个模块源自 https://github.com/eclipse/che/blob/da18cd1867210f87a6071ed65930fb47fb8bb775/ide/che-ide-gwt-app/pom.xml[`che-ide-gwt-app`], 它通过  https://github.com/eclipse/che/blob/5a6d3910b268feb3c4e67c2ff9aa5640410bf777/ide/che-ide-full/pom.xml[`che-ide-full`] 间接的含了所有的依赖。 因此，在 `che-ide-full` 里声明了对所有客户端的依赖。

然而，如果你构建一个定制的程序集并在你的插件中提供客户端的功能，一定要把它添加到 *assembly-ide-war* 根 pom.xml中的dependencies内。见：link:ide-extensions-gwt.html[IDE 扩展]。

定制插件通常是在这个模块里扩展的。

[id="assembly-wsagent-war"]
== assembly-wsagent-war

构建该模块的工件包含了所有服务器端的plugin组件，以jar形式打包。根 `pom.xml` 中包含对插件的依赖声明，所依赖的插件随工作空间的agent一起部署，这也是对定制的插件的依赖关系说明应该添加的地方。一旦构建， `assembly-wsagent-war` 作为 `ROOT.war`被拷贝到ws-agent Tomcat下的 `webapps` 下。  定制插件通常在这个模块里进行扩展。

[id="assembly-wsagent-server"]
== assembly-wsagent-server

这个模块把 `ROOT.war` 打包进Tomcat的 `webapps` 并增加配置文件。 这个Tomcat被打包为tar.gz 文档，然后被放到由 `assembly-main` 构建生成的主Tomcat中。

[id="assembly-wsmaster-war"]
== assembly-wsmaster-war

工作空间服务器作为Che平台的核心包含link:rest-api.html[workspace API], 用户信息管理和设置, link:spi-implementation.html[runtime基础设施的实现]。通常在定制程序集中作为依赖项使用。然而，它也可以被扩展，例如，提供对新基础设施的支持。

[id="assembly-main"]
== assembly-main

该模块正如其名 - 它作为主程序集把所有组件打包到Tomcat 服务器中。这些组件包括作为 `api.war` 的wsmaster, 作为 `dashboard.war` 的Dashboard, 文档 - `docs.war` 和Swgger UI - `swagger.war`, agents 如terminal和ws-agent(这些包被放到位于最终文档根下的 `lib` 目录中，由Che master提取和供给，遂使得它们可以被 link:installers.html[installers]下载). 

[id="custom-assemblies"]
== Custom Assemblies

你可以构建你自定义的Che程序集。为此，你不必要clone/copy整个的Che的源代码。所有工件可以被当做依赖项使用。而且，不像Che源代码中的程序集，定制化的程序集能使用为服务器和客户端使用小的工件。


这有一个 https://github.com/che-samples/che-ide-server-extension[示例] 是关于有两个插件的定制的Che程序集的，一个插件是Server， 一个是客户端的。你可以clone这个库并把它作为你定制Che程序集的开始。


请注意这个示例使用核心工件作为依赖项既有 https://github.com/che-samples/che-ide-server-extension/blob/master/assembly/assembly-ide-war/pom.xml#L31-L35[客户端]:

[source,xml]
----
<dependency>
    <groupId>org.eclipse.che.core</groupId>
    <artifactId>che-ide-core</artifactId>
    <type>gwt-lib</type>
</dependency>
----

也有 https://github.com/che-samples/che-ide-server-extension/blob/master/assembly/assembly-wsagent-war/pom.xml#L22-L26[服务端]

[source,xml]
----
<dependency>
    <groupId>org.eclipse.che.core</groupId>
    <artifactId>che-wsagent-core</artifactId>
    <type>war</type>
</dependency>
----

核心工件包含平台组件和插件的最小集，能创建和启动工作空间，创建或导入Project,在编辑器中打开和编辑文件。

你可以使用包含所有Che插件的所有工件：

客户端:

[source,xml]
----
<dependency>
    <groupId>org.eclipse.che.core</groupId>
    <artifactId>che-ide-full</artifactId>
    <type>gwt-lib</type>
</dependency>
----

你可以包含除某个插件外的完整的IDE工件:

[source,xml]
----
<dependencies>
   <dependency>
      <groupId>org.eclipse.che.core</groupId>
      <artifactId>che-ide-full</artifactId>
      <exclusions>
         <exclusion>
            <artifactId>che-plugin-product-info</artifactId>
            <groupId>org.eclipse.che.plugin</groupId>
         </exclusion>
      </exclusions>
  </dependency>
</dependencies>
<build>
    <plugins>
       <plugin>
          <groupId>org.eclipse.che.core</groupId>
          <artifactId>che-core-gwt-maven-plugin</artifactId>
          <version>${project.version}</version>
          <executions>
             <execution>
                <goals>
                   <goal>process-excludes</goal>
                </goals>
             </execution>
          </executions>
       </plugin>
    </plugins>
 </build>
----

服务器端:

[source,xml]
----

<dependency>
    <groupId>org.eclipse.che</groupId>
    <artifactId>assembly-wsagent-war</artifactId>
    <type>war</type>
</dependency>
----

这两个 `pom.xml` 文件是增加定制插件的入口。这个程序集包括两个插件，它们被声明在：

* https://github.com/che-samples/che-ide-server-extension/blob/master/pom.xml#L54-L64[root pom.xml] - 工件版本默认为项目版本。需要声明这些依赖项以遵循Che中的依赖项收敛规则（即，所有依赖项必须在Che `maven-depmgt-pom' 中或在程序集的根pom中声明）。`Maven-depmgt-pom` 的parent带来的是一组执行器插件，如格式化、依赖性管理、源验证等。

[source,xml]
----
<dependency>
    <groupId>org.eclipse.che.sample</groupId>
    <artifactId>plugin-serverservice-server</artifactId>
    <version>${project.version}</version>
</dependency>
----

* https://github.com/che-samples/che-ide-server-extension/blob/master/assembly/assembly-ide-war/pom.xml#L36-L40[assembly-ide-war pom]:

[source,xml]
----
<dependency>
    <groupId>org.eclipse.che.sample</groupId>
    <artifactId>plugin-serverservice-ide</artifactId>
    <type>gwt-lib</type>
</dependency>
----

这样，你的客户端插件被包含到 `ide.war` 中。我们使用 https://maven.apache.org/plugins/maven-war-plugin/overlays.html[Maven’s overlays feature] 打包定制插件到生成的工件中。

* https://github.com/che-samples/che-ide-server-extension/blob/master/assembly/assembly-wsagent-war/pom.xml#L27-L30[assembly-wsmaster-war pom]:

[source,xml]
----
<dependency>
    <groupId>org.eclipse.che.sample</groupId>
    <artifactId>plugin-serverservice-server</artifactId>
</dependency>
----

如果两个都被作为依赖项在 `pom.xml` 中声明，你的定制插件被打包为jar并自动添加到继承的 `wsagent` 工件中。作为结果，最终的 `.war` 工件将包含定制的jar。

[id="update-assembly"]
== 更新程序集

在 `pom.xml` 同时更新:

[source,xml]
----
<parent>
    <artifactId>maven-depmgt-pom</artifactId>
    <groupId>org.eclipse.che.depmgt</groupId>
    <version>6.0.0-M4</version>
</parent>
----

和

[source,xml]
----
<properties>
    <che.version>6.0.0-M4</che.version>
</properties>
----

保持这些版本一致以避免构建失败和不兼容是非常重要的。也推荐要保持自己工件的版本和父版本的一致。

[id="next-steps"]
== 下一步

现在，你已经了解了Che 程序集的知识和复制了一个程序集示例，让我们更近的了解Eclipse Che link:ide-extensions-gwt.html[客户端] 和 link:server-side-extensions.html[服务端] 插件吧.
