---
title: "构建需求"
keywords: java. maven, node, npm
tags: [dev-docs]
sidebar: che_6_docs
permalink: che-6/build-reqs.html
redirect_from: build-reqs.html
folder: che-6/developer-guide
---


[id="build-command"]
== 构建命令

`mvn clean install`

在定制的程序集或Che仓库的根目录下执行这个命令。为了让构建执行的更快，你可以使用下面的参数：

`-Dskip-enforce -DskipTests -Dskip-validate-sources -Dfindbugs.skip -DskipIntegrationTests=true -Dmdep.analyze.skip=true`

如果你计划做一个PR到Che上游，要确保构建时使用命令 `mvn clean install` 让所有的测试和强制检查是成功的。如果你有足够多的CPU可用，你可以使用命令 `-Dgwt.compiler.localWorkers=4` ，这会使用4个CPU核心做GWT的编译。

[id="pre-reqs"]
== 预先准备

* JDK 1.8.0_130+
* Maven 3.3.5+
* Go 1.8+

默认情况下，Che是用Docker配置文件构建的，这意味着仪表板是在Docker容器中构建的。不过，您可以使用不同的配置文件-`mvn clean install-P`-在这种情况下，需要使用下面的Node.JS版本：

* Node.JS 5.4+

如果你的 link:assemblies.html[定制程序集] 并没有改变 Dashboard, https://github.com/eclipse/che/tree/master/agents[Golang agents] and link:what-are-workspaces.html#bootstrapper[bootstrapper], 你仅需要安装JDK 1.8.0_130+。

最低的配置是 2 CPUs 和 8GB RAM (推荐).

[id="build-in-docker"]
== 在 Docker中构建

你可以使用 https://github.com/eclipse/che/blob/master/dockerfiles/dev/Dockerfile[开发镜像]:

`docker run -ti -v ~/.m2:/home/user/.m2 -v /path/to/che/assembly:/che eclipse/che-dev:nightly sh -c "mvn clean install"`

我们推荐挂载Maven仓库 (`-v ~/.m2:/home/user/.m2`) 以持久化依赖项而加速构建。

[id="build-in-che"]
== 在Che中构建

参见: link:che-in-che-quickstart.html[Che在Che中的快速开始]

[id="enforcers"]
== 强制执行

在父pom文件中有一些强制执行的事项

*许可*

所有的源代码文件中都应该有许可信息。如果你因为缺少了许可而构建失败，你可以执行命令 `mvn license:format`

*依赖项的收敛*

需要遵循CHE中的依赖性收敛规则声明您的自定义依赖项（即，所有依赖项必须声明在Che`maven-depmgt-pom'中或程序集的根pom中）。

*格式*

参见: https://github.com/eclipse/che/wiki/Development-Workflow#code-style[代码规范]
