---
title: "IDE 扩展: GWT"
keywords: framework, extensions, gwt, client side
tags: [extensions, assembly, dev-docs]
sidebar: che_6_docs
permalink: che-6/ide-extensions-gwt.html
redirect_from: ide-extensions-gwt.html
folder: che-6/developer-guide
---


[id="ide-extension-structure"]
== IDE 扩展结构

让我们仔细查看一个IDE扩展应该有什么样的结构：

----
ide
├─ src                                              // sources folder
│  └─ main
│     ├─ java
│     │  └─ org.eclipse.che.plugin.menu.ide
│     │     ├─ ...
│     │     ├─ inject
│     │     │  └─ SampleMenuGinModule.java          // GIN module
│     │     └─ SampleMenuExtension.java             // IDE extension class
│     ├─ resources
│     │  └─ org.eclipse.che.ide.ext.demo.client
│     └─ module.gwt.xml                             // template for generating GWT module [1]
├─ target                                           // build output
│  └─ classes
│     ├─ META-INF
│     │  └─ gwt
│     │     └─ mainModule                           // contains GWT module name [2]
│     └─ org.eclipse.che.plugin.menu
│        ├─ ...
│        └─ SampleMenuExtension.gwt.xml             // generated GWT module [3]
└─ pom.xml
----

链接: https://tbroyer.github.io/gwt-maven-plugin/generate-module-mojo.html[1] https://tbroyer.github.io/gwt-maven-plugin/generate-module-metadata-mojo.html[2] https://tbroyer.github.io/gwt-maven-plugin/generate-module-mojo.html[3]

[id="pom.xml"]
== pom.xml

在Che IDE插件的pom.xml中有几个重要的部分：

* Maven 项目的packaging类型是 `gwt-lib` ,它触发 Maven https://tbroyer.github.io/gwt-maven-plugin/lifecycles.html#GWT_Library:_gwt-lib[`gwt-lib`] 生命周期，构建出一个 https://tbroyer.github.io/gwt-maven-plugin/artifact-handlers.html#GWT_Library:_gwt-lib[GWT library]：
+
[source,xml]
----
<packaging>gwt-lib</packaging>
----
* 依赖于Che IDE API库，提供一个 https://docs.google.com/spreadsheets/d/1ijapDnl1G7svy7sIKgTntyTuVsnd9nFcH0-357C0MxE/edit#gid=0[API集合] 用于扩展Che IDE：
+
[source,xml]
----
<dependency>
    <groupId>org.eclipse.che.core</groupId>
    <artifactId>che-core-ide-api</artifactId>
</dependency>
----
* GWT模块的名字在  `gwt-maven-plugin` 的 `configuration` 中定义：
+
[source,xml]
----
<plugin>
    <groupId>net.ltgt.gwt.maven</groupId>
    <artifactId>gwt-maven-plugin</artifactId>
    <extensions>true</extensions>
    <configuration>
        <moduleName>org.eclipse.che.plugin.menu.SampleMenuExtension</moduleName>
    </configuration>
</plugin>
----
+
更多关于生成GWT模块的内容，请阅读 `gwt:generate-module` https://tbroyer.github.io/gwt-maven-plugin/generate-module-mojo.html[mojo description]。GWT 库是一个JAR,它包含着编译类，项目的资源，GWT模块描述符，和可能的其它的某些GWT相关文件。

[id="gwt.xml"]
== gwt.xml

项目的 `*.gwt.xml` 文件产生在 `gwt-lib` 的Maven生命周期，包含：

* 对缺省的源代码文件夹的声明：
+
[source,xml]
----
<source path="client"/>
<source path="shared"/>
<super-source path="super"/>
----
* `<inherits/>` 指令用于项目的 _直接_ 依赖项，它们被打包成一个 `gwt-lib`。

_可选的_ 模板可在 `src/main/module.gwt.xml` 中提供以生成项目的 `*.gwt.xml` 文件。

你可能需要一个模板的最通常的情况是：

* 需要重载缺省的源代码文件夹, 比如 https://github.com/eclipse/che/blob/f15fbf1cb1248d18acc3ee6fdc41766946ea4a3b/plugins/plugin-java/che-plugin-java-ext-lang-client/src/main/module.gwt.xml#L18[这]；
* 需要增加 `<inherits/>` directive 给不打包为 `gwt-lib` 工件的GWT库 (不包含GWT相关的元信息)。

[id="consuming-shared-libs"]
== 使用共享库

共享库不需要任何在pom.xml中的GWT特定文件和配置被GWT库使用。

要使用GWT库中共享的代码：

* 声明对"normal"工件的依赖（带编译类的JAR）
* 声明对"sources"的依赖（通过`<classifier>sources</classifier>`）。

参考示例见 https://github.com/eclipse/che/blob/19f5fd1f5ae8f165b7306e71cb0d58c2082fafab/plugins/plugin-python/che-plugin-python-lang-ide/pom.xml#L49-L57[这].

[id="ide-extension-class"]
== IDE 扩展类

Che IDE 插件有一个入口 - 使用 https://github.com/eclipse/che/blob/master/ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/extension/Extension.java[`@org.eclipse.che.ide.api.extension.Extension`] 注解的Java类。插件入口在完成Che IDE的核心部分的初始化后立即被调用。

这里是一个插件的入口，它使用 link:actions.html[IDE actions]增加一个新的顶层菜单组：

[source,java]
----
package org.eclipse.che.plugin.menu.ide;

import static org.eclipse.che.ide.api.action.IdeActions.GROUP_HELP;
import static org.eclipse.che.ide.api.action.IdeActions.GROUP_MAIN_MENU;
import static org.eclipse.che.ide.api.constraints.Anchor.AFTER;

import com.google.inject.Inject;
import org.eclipse.che.ide.api.action.ActionManager;
import org.eclipse.che.ide.api.action.DefaultActionGroup;
import org.eclipse.che.ide.api.constraints.Constraints;
import org.eclipse.che.ide.api.extension.Extension;
import org.eclipse.che.plugin.menu.ide.action.SampleAction;

@Extension(title = "Sample Menu")
public class SampleMenuExtension {

  private static final String SAMPLE_GROUP_MAIN_MENU = "Sample";

  @Inject
  private void prepareActions(SampleAction sampleAction, ActionManager actionManager) {

    DefaultActionGroup mainMenu = (DefaultActionGroup) actionManager.getAction(GROUP_MAIN_MENU);

    DefaultActionGroup sampleGroup =
        new DefaultActionGroup(SAMPLE_GROUP_MAIN_MENU, true, actionManager);
    actionManager.registerAction("sampleGroup", sampleGroup);
    mainMenu.add(sampleGroup, new Constraints(AFTER, GROUP_HELP));

    actionManager.registerAction("sayHello", sampleAction);
    sampleGroup.add(sampleAction, Constraints.FIRST);
  }
}
----

[id="dependency-injection"]
== 依赖注入

Che IDE使用 https://code.google.com/archive/p/google-gin/[Google GIN] 进行依赖注入。Che IDE插件提供GIN模块。插件的GIN模块需要使用 https://github.com/eclipse/che/blob/master/ide/che-core-ide-api/src/main/java/org/eclipse/che/ide/api/extension/ExtensionGinModule.java[`@org.eclipse.che.ide.api.extension.ExtensionGinModule`] 标记进行注解以便能被IDE找到。


这里是一个插件的GIN模块

[source,java]
----
package org.eclipse.che.plugin.menu.ide.inject;

import com.google.gwt.inject.client.AbstractGinModule;
import org.eclipse.che.ide.api.extension.ExtensionGinModule;

@ExtensionGinModule
public class SampleMenuGinModule extends AbstractGinModule {

  @Override
  protected void configure() {}
}
----

在这个示例中因为插件不真的需要放任何东西到容器中，所以并不真的需要扩展的GIN模块。更多内容请阅读 link:guice.html[依赖注入] 和  https://github.com/eclipse/che/blob/master/plugins/plugin-csharp/che-plugin-csharp-lang-ide/src/main/java/org/eclipse/che/plugin/csharp/ide/inject/CSharpGinModule.java[Gin 模块示例]。

[id="extension-points"]
== 扩展点

你可以提供或自定义已有的 link:actions.html[actions], link:parts.html[parts], link:themes.html[themes] 和 link:editor.html[editor]. 这个示例注册了一个新的action。

[id="debugging-with-super-devmode"]
== 使用Super DevMode调试

有两种可以选的方式启动GWT Super DevMode，依赖Che源代码的状态：是否构建过，因为一些源代码是在Maven的构建过程中产生的。

* Case 1: Che 源代码已经被构建。使用下面的命令：

`mvn gwt:codeserver -pl :che-ide-gwt-app -am -Dmaven.main.skip -Dmaven.resources.skip -Dche.dto.skip -Dskip-enforce -Dskip-validate-sources`

* Case 2: Che 源代码尚没有被构建，例如，刚刚被clone的代码或刚执行了 `mvn clean` 或你仅不需要构建整个项目。使用下面的命令：

`mvn gwt:codeserver -pl :che-ide-gwt-app -am -Dskip-enforce -Dskip-validate-sources`

第二个命令需要 _更多时间_ 启动GWT 代码服务(CodeServer)因为它为每个maven模块执行 `process-class` 构建阶段。因此，尽量优先使用第一个命令吧。 

*注意*, 两个命令都必须要在Che的项目根目录下执行。

一旦代码服务启动了，打开提示的URL，把标签拖到你的标签条上。注意你可能会遇到错误提示说在这个页面中没有GWT模块。这是因为IDE是在iframe里打开的。仅仅需要，从url中剪切掉 `dashboard/#/ide`。要调试客户端代码，要遵照的说明参见 link:che-in-che-quickstart.html#develop-and-debug-client-side[快速入门]。

[id="run-in-che"]
== 在Che里运行

一旦你的扩展就绪，你可以构建，运行和调试它在 link:che-in-che-quickstart.html[Che自身内]。只是使用一个已有的示例和增加带有所有依赖项的自定义插件。

[id="add-to-a-custom-assembly"]
== 增加一个自定义的程序集

你可以在Che外和/或使用任何的IDE构建你自定义的 link:assemblies.html[Che程序集]以开发扩展。一旦完成，在assembly根目录下运行 `mvn clean install`，生成一个Tomcat集束(bundle)，直接地可以把它用于在 link:docker-config.html#development-mode[Docker] 或 link:openshift-config.html#development-mode[OpenShift]上部署。
