---
title: "快速启动"
keywords: docker, installation, minishift, openshift
tags: [installation, docker]
sidebar: che_6_docs
permalink: che-6/quick-start.html
redirect_from: quick-start.html
folder: che-6/overview
---

Eclipse Che是开发者工作空间服务器和云IDE。你可以使用不同的容器编排引擎（如Docker或OpenShift）安装、运行和管理Eclipse Che。

Eclipse Che有两种可用的方式：

* *单用户*: 这适用于个人桌面环境。
* *多用户*: 这是适用于组织和开发者团队的，一种高级安装方式。

[id="docker"]
== 在Docker上以单用户方式运行Che

.前提条件

* 已安装最新的Docker(Docker 17+)
* 在macOS，创建IP别名(IP alias)。在终端中，运行：
+
----
# ifconfig la0 alias $IP
----
+
有两种可以获得 `$IP` 的方式，通过 *Preferences > Advanced > Docker subnet* 或者运行
+
----
$ docker run --rm --net host eclipse/che-ip:nightly
----

.过程

为在单用户模式运行Che，输入：

----
$ docker run -ti -v /var/run/docker.sock:/var/run/docker.sock -v /local/path:/data eclipse/che start
----

需注意 `/local/path` 可以是在你本机机器上的任何路径，它是你想存储Che数据和项目的地方。

.下一步

link:creating-starting-workspaces[创建和启动你第一个工作空间], 导入一个 link:ide-projects[项目], 并 link:commands-ide-macro[构建和运行] 你的项目。

.其它的资料

* link:docker-single-user.html[Docker上的单用户]
* link:docker-multi-user.html[Docker上的多用户]
* link:docker-config.html[Docker上的配置]
* link:docker-cli.html[Docker上的Che CLI]

[id="openshift"]
== 在OpenShift上运行单用户的Che

.前提条件

* 使用最新版本的 https://docs.openshift.org/latest/minishift/getting-started/index.html[MiniShift]. 参见 https://github.com/minishift/minishift-addons/tree/master/add-ons/che[MiniShift add-on for Che].

为在Minishift上以单用户模式运行Che，执行：

----
$ git clone https://github.com/minishift/minishift-addons
$ minishift addons install <path_to_minishift-addons-clone>/add-ons/che
$ minishift addons enable che
$ minishift addons apply \
    --addon-env CHE_DOCKER_IMAGE=eclipse/che-server:nightly \
    --addon-env OPENSHIFT_TOKEN=$(oc whoami -t) \
    che
----

.下一步

link:creating-starting-workspaces.html[创建和启动你的首个 workspace], 导入一个 link:ide-projects.html[project], and link:commands-ide-macro.html[构建和运行] 你的project。

.其它的资料

* link:openshift-single-user.html[OpenShift上的单用户模式]
* link:openshift-multi-user.html[OpenShift上的多用户模式]
* link:openshift-config.html[OpenShift上的配置]

下面的资料是Che提供的关于OpenShift变体的更多信息：

* https://www.openshift.com/container-platform/index.html[OpenShift Container Platform (OCP)]: 用于在你数据中心内安装的OpenShift on-premise.
* https://www.openshift.com/features/index.html[OpenShift Online (OSO)]: 托管于公有云由Red Hat管理的随需提供的OpenShift.
* https://access.redhat.com/products/openshift-dedicated-red-hat/[OpenShift Dedicated (OCD)]: 带有你专有OpenShift集群的由Red Hat管理的企业公有云.
* https://www.openshift.org/minishift/[MiniShift]: 在你本地环境运行OpenShift.
